# Generated by Django 3.2.16 on 2022-10-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artiste_id',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='song_id_lyric',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artiste_id_song',
        ),
    ]
